branches:
    only:
    - master
    
 cache:
    directories:
    -$HOME/cache
    
sudo: required

service:
    - docker
    
    script: 
        - docker build -t webapp -f ./Docker/DockerFile . 
        - docker run -it --rm -v $HOME/cache:/root/.nuget/packages -p 8080:5000 webapp:test